# https://github.com/atom/ci

language: generic

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.3

install:
  - |
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      # Build Csound.
      sudo apt-get --assume-yes install libsndfile1-dev
      wget --no-verbose https://github.com/csound/csound/archive/6.14.0.tar.gz
      tar -xf 6.14.0.tar.gz
      cd csound-6.14.0
      mkdir build
      cd build
      # When built with DSSI <http://dssi.sourceforge.net> opcodes, attempting
      # to produce sound from Csound 6.10.0 and later on Travis CI results in a
      # segmentation fault (see https://github.com/csound/csound/issues/901).
      cmake .. -DBUILD_DSSI_OPCODES=OFF
      make
      sudo make install
      sudo ldconfig
      # Get csound-api dependencies.
      sudo apt-get --assume-yes install libboost-dev
    else
      brew uninstall python@2
      brew install csound
    fi

script: curl --silent https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
